### ISSUE TITLE
Shouldn't default to globally named

### ISSUE THREAD

**Issue by ConnorRigby** [jjcarstens/extty#2]
While the ExTTY GenServer can be used as a normal unnamed process, it's impossible to start the  GenServer without naming it due to how the default `start_link` function is implemented.

**Comment by jjcarstens** [comment]
I just tried `name: nil` thinking it would fully break, but it seems to have worked. Does this accomplish what you were hoping?

```elixir
iex(1)> ExTTY.start_link(name: nil)
{:ok, #PID<0.226.0>}
```

Digging a bit more into [`GenServer.start_link`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/gen_server.ex#L936) it seems `name: nil` is viable and should be expected to create unnamed process.
